language: python

matrix:
  include:
    - name: CUDA 10
      env:
        - CUDA=10.0
        - CUDA_SHORT=10.0
        - UBUNTU_VERSION=ubuntu1804
      dist: bionic

install:
  - pip install tensorflow==1.15
  - pip install -e python

script:
  - python sample/tensorflow/benchmark.py -p fp32
  - python sample/tensorflow/benchmark.py -p fp16
